/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TitleholdersRouteImport } from './routes/titleholders'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as MediaRouteImport } from './routes/media'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DelegatesRouteImport } from './routes/delegates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as AdvocacyRouteImport } from './routes/advocacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TitleholdersRoute = TitleholdersRouteImport.update({
  id: '/titleholders',
  path: '/titleholders',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegatesRoute = DelegatesRouteImport.update({
  id: '/delegates',
  path: '/delegates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocacyRoute = AdvocacyRouteImport.update({
  id: '/advocacy',
  path: '/advocacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/sponsors': typeof SponsorsRoute
  '/titleholders': typeof TitleholdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/sponsors': typeof SponsorsRoute
  '/titleholders': typeof TitleholdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/competition': typeof CompetitionRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/sponsors': typeof SponsorsRoute
  '/titleholders': typeof TitleholdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advocacy'
    | '/competition'
    | '/contact'
    | '/delegates'
    | '/events'
    | '/media'
    | '/sponsors'
    | '/titleholders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advocacy'
    | '/competition'
    | '/contact'
    | '/delegates'
    | '/events'
    | '/media'
    | '/sponsors'
    | '/titleholders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advocacy'
    | '/competition'
    | '/contact'
    | '/delegates'
    | '/events'
    | '/media'
    | '/sponsors'
    | '/titleholders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvocacyRoute: typeof AdvocacyRoute
  CompetitionRoute: typeof CompetitionRoute
  ContactRoute: typeof ContactRoute
  DelegatesRoute: typeof DelegatesRoute
  EventsRoute: typeof EventsRoute
  MediaRoute: typeof MediaRoute
  SponsorsRoute: typeof SponsorsRoute
  TitleholdersRoute: typeof TitleholdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/titleholders': {
      id: '/titleholders'
      path: '/titleholders'
      fullPath: '/titleholders'
      preLoaderRoute: typeof TitleholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegates': {
      id: '/delegates'
      path: '/delegates'
      fullPath: '/delegates'
      preLoaderRoute: typeof DelegatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocacy': {
      id: '/advocacy'
      path: '/advocacy'
      fullPath: '/advocacy'
      preLoaderRoute: typeof AdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvocacyRoute: AdvocacyRoute,
  CompetitionRoute: CompetitionRoute,
  ContactRoute: ContactRoute,
  DelegatesRoute: DelegatesRoute,
  EventsRoute: EventsRoute,
  MediaRoute: MediaRoute,
  SponsorsRoute: SponsorsRoute,
  TitleholdersRoute: TitleholdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
